### ISSUE TITLE
Automated testing - basic transfer

### ISSUE THREAD

**Issue by lucy-meachem** [pax2pay/client-js#10]
xfers are modulr only, you have a choice of a beneficiary, funding account or non-beneficiary (can make beneficiary from this rq)

- [ ] make basic test structure 2pt
- [ ] do beneficiary test 0.5pt
- [ ] do funding account test 0.5pt
- [ ] do non-beneficiary test (with/without create) 1pt
