### ISSUE TITLE
Automated testing - booking info

### ISSUE THREAD

**Issue by lucy-meachem** [pax2pay/client-js#9]
test those booking infos boys

 - [ ] add a five-fields booking info to a freshly made card #12 1pt
  - [ ] get that booking info & asserts #13  1pt
  - [ ] add a flight booking info to a freshly made card #14 1pt
  - [ ] get that booking info & asserts #15 1pt
 - [ ]  get that booking info as five-fields & asserts #16 1pt
 - [ ]  add second booking info to card, should fail #17 1pt
